[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-vcs>=0.4",
  "hatchling>=1.25",
]

[project]
name = "pch"
description = "Extra hooks for pre-commit."
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "sax", email = "s.apostolico@gmail.com" },
]
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dynamic = [
  "version",
]
dependencies = [
    "pre-commit>=4.3.0",
]
urls.Homepage = "https://github.com/saxix/pch"
scripts.check-run-command = "pch.check_run_command:check_run_command"
scripts.check-forbidden = "pch.check_forbidden:check_forbidden"
scripts.check-missed-migrations = "pch.check_missed_migrations:check_missed_migrations"
scripts.check-untracked = "pch.check_untracked:check_untracked"

[dependency-groups]
dev = [
  "mypy>=1.14.1",
  "pytest>=8.3.5",
  "pytest-coverage>=0",
  "ruff>=0.11.9",
  "tox>=4.25",
]

docs = [
]

mypy = [
  "djangorestframework-stubs",
  "lxml-stubs",
  "mypy",
  "types-defusedxml",
  "types-gevent",
  "types-html5lib",
  "types-jmespath",
  "types-markdown",
  "types-psycopg2",
  "types-pygments",
  "types-python-dateutil",
  "types-pytz",
  "types-qrcode",
  "types-requests",
]

[tool.hatch]
build.hooks.vcs.version-file = "src/pch/version.py"
version.source = "vcs"
raw-options = { root = "../.." }

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.build.targets.sdist]
ignore-vcs = true
include = [
  "src/pch/**/*.*",
]

[tool.hatch.build.targets.wheel]
packages = [
  "src/pch",
]

[tool.uv]
package = true
